repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
        files: src/|test-resources/|demo/
      - id: end-of-file-fixer
        files: src/|test-resources/|demo/
      - id: mixed-line-ending
        files: src/|test-resources/|demo/
  - repo: local
    hooks:
      - id: toml-fmt
        name: toml-fmt
        language: system
        entry: taplo fmt
      - id: cargo-fmt
        name: cargo fmt
        language: system
        entry: bash -c 'cargo fmt'
        types: [rust]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: forbid-tabs
        files: src/
      - id: remove-tabs
        files: src/
      - id: insert-license
        files: \.rs$
        args:
          - --license-filepath
          - license_header.txt
          - --comment-style
          - /*| | */

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.1' 
    hooks:
    -   id: autopep8
        files: demo/
        exclude: only_lists.py

    repos:
      - repo: https://github.com/prettier/prettier
        rev: '2.3.0'  # Use the ref you want to point at
        hooks:
          - id: prettier
            files: experimental/
