repos:
  - repo: local
    hooks:
      - id: toml-fmt
        name: toml-fmt
        language: system
        entry: taplo fmt
      - id: cargo-fmt
        name: cargo fmt
        language: system
        entry: bash -c 'cargo fmt --manifest-path polyglot/piranha/Cargo.toml'
        types: [rust]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: forbid-tabs
      - id: remove-tabs
      - id: insert-license
        files: \.rs$
        args:
          - --license-filepath
          - polyglot/piranha/license_header.txt
          - --comment-style
          - /*| | */
