[[rules]]

name = "directExecutor"

query = """((method_invocation
 name: (identifier ) @tag1
 arguments: (argument_list ) @tag2) @tag3
(#eq? @tag1 "directExecutor"))"""

replace_node = "@tag3"

replace = "GuavaContextWrappers.wrap(MoreExecutors.@tag3)"

[[rules.filters]]

enclosing_node = "(expression_statement) @parent"

not_contains = """[
((method_invocation
 object: (identifier ) @tag5
 name: (identifier ) @tag6
 arguments: (argument_list
  (method_invocation
   object: (identifier ) @tag7
   name: (identifier ) @tag8
   arguments: (argument_list ) @tag9) @tag10) @tag11) @tag12
(#eq? @tag5 "GuavaContextWrappers")
(#eq? @tag6 "wrap")
(#eq? @tag7 "MoreExecutors")
(#eq? @tag8 "directExecutor"))
]"""