[package]
name = "rust_source_diff"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "4.0.3", features = ["derive"] }
tree-sitter = "0.19.1"
tree-sitter-java = "0.19.0"
diffr = "0.1.4"
getset = "0.1.2"
derive_builder = "0.12.0"
regex = "1.8.2"
