# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Legacy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    working-directory: legacy/javascript

jobs:
  detect:
    uses: ./.github/workflows/detect_changes.yml

  build_JS:
    runs-on: ubuntu-latest
    needs: detect
    if: ${{ github.event_name == 'push' || needs.detect.outputs.legacy == 'true' }}
    env:
      HUSKY_SKIP_INSTALL: 1

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - run: npm test
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Format
        run: |
          npm ci
          npm run check_format
      - uses: actions/checkout@v2
      - uses: hallee/eslint-action@1.0.3
        with:
          # GITHUB_TOKEN in forked repositories is read-only
          # https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
          repo-token: ${{secrets.GITHUB_TOKEN}}
          source-root: legacy/javascript

  build_java:
    name: "JDK ${{ matrix.java }} on ${{ matrix.os }}"
    strategy:
      matrix:
        include:
          - os: macos-latest
            java: 8
          - os: macos-latest
            java: 11
          - os: ubuntu-latest
            java: 8
          - os: ubuntu-latest
            java: 11
      fail-fast: false
    runs-on: ${{ matrix.os }}
    needs: detect
    if: ${{ github.event_name == 'push' || needs.detect.outputs.legacy == 'true' }}
    steps:
      - name: Check out Piranha sources
        uses: actions/checkout@v2
      - name: "Set up JDK ${{ matrix.java }}"
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build and test using Gradle and Java
        uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: ./legacy/java
          wrapper-directory: ./legacy/java
          arguments: verGJF build
