name: Release Polyglot Piranha
on:
  workflow_dispatch:
jobs:
  macos_build:
    name: '02 - macOS'
    runs-on: [macos-12]
    strategy:
      matrix:
        arch: ['x86_64', 'arm64']
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.16
      CXXFLAGS: -stdlib=libc++ -mmacosx-version-min=10.16
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build wheel with Maturin
        run: |
          pip install --upgrade maturin
          maturin build --release -o dist
      - name: Pypi Release for ubuntu-latest
        run: |
          pip install twine
          twine upload --skip-existing -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*
