name: Release Polyglot Piranha
on:
  workflow_dispatch:
jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: dtolnay/rust-toolchain@stable
    - uses: PyO3/maturin-action@v1.36.0
      with:
        command: build
        manylinux: auto
        args: --release --sdist -o dist
    # - name: Upload wheels
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: wheels
    #     path: dist
    - name: Pypi Release for ubuntu-latest
      run: |
        pip install twine
        twine upload --repository testpypi --skip-existing -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*
  
  # build_mac_os:
  #   needs: build_ubuntu
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.9
  #   - name: Build wheel with Maturin
  #     run: |
  #       pip install --upgrade maturin
  #       maturin build --release -o dist
  #   - name: Build wheel with Maturin - universal2
  #     env:
  #       DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  #       SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
  #       MACOSX_DEPLOYMENT_TARGET: 10.9
  #     run: |
  #       rustup target add aarch64-apple-darwin
  #       pip install --upgrade maturin
  #       maturin build --release -o dist --universal2
  #   - name: Pypi Release for ubuntu-latest
  #     run: |
  #       pip install twine
  #       twine upload --skip-existing -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*
